"""Offline regression checks for PostgreSQL staging DDL generation."""
import unittest

from scripts.build_pg_schema import generate, quote, sqlite_schema


class StagingSchemaTests(unittest.TestCase):
    def test_all_operational_and_security_tables_present(self):
        ddl, tables = generate()
        self.assertGreaterEqual(len(tables), 26)
        for table in ("customers", "opportunities", "inventory_lots",
                      "quality_cases", "finance_transactions", "audit_log",
                      "system_settings", "regulatory_items"):
            self.assertIn(table, tables)
            self.assertIn('CREATE TABLE "' + table + '"', ddl)

    def test_primary_keys_and_foreign_keys(self):
        ddl, _ = generate()
        self.assertIn('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', ddl)
        self.assertIn('FOREIGN KEY ("customer_id") REFERENCES "customers" ("id")', ddl)
        self.assertIn('UNIQUE ("customer_id", "product_id")', ddl)
        self.assertIn('"setting_key" TEXT NOT NULL', ddl)

    def test_foreign_keys_created_after_all_tables(self):
        ddl, tables = generate()
        last_create = max(ddl.index('CREATE TABLE "' + table + '"') for table in tables)
        first_fk = ddl.index('ALTER TABLE "')
        self.assertGreater(first_fk, last_create)
        self.assertIn('ADD CONSTRAINT "fk_opportunities_', ddl)
        self.assertIn('FOREIGN KEY ("customer_id") REFERENCES "customers" ("id")', ddl)
        self.assertTrue(ddl.strip().endswith("COMMIT;"))

    def test_additional_columns_are_preserved(self):
        ddl, _ = generate()
        for column in ('"quality_hold_kg"', '"credit_limit"', '"lost_reason"'):
            self.assertIn(column, ddl)

    def test_staging_is_explicit_and_no_secrets(self):
        ddl, _ = generate()
        self.assertIn('CREATE SCHEMA IF NOT EXISTS "ct_staging"', ddl)
        self.assertIn('SET LOCAL search_path TO "ct_staging"', ddl)
        self.assertIn("BEGIN;", ddl)
        self.assertIn("COMMIT;", ddl)
        self.assertNotIn("DATABASE_URL", ddl)
        self.assertNotIn("postgresql://", ddl)

    def test_deterministic_and_safe_identifier(self):
        self.assertEqual(generate()[0], generate()[0])
        with self.assertRaises(ValueError):
            quote('public; DROP TABLE customers')

    def test_source_introspection(self):
        with sqlite_schema() as conn:
            count = conn.execute("SELECT count(*) FROM sqlite_master WHERE type='table'").fetchone()[0]
            self.assertGreaterEqual(count, 26)


if __name__ == "__main__":
    unittest.main()
