"""Generate reviewable PostgreSQL staging DDL from the current SQLite definitions.

Offline only: never connects to Supabase or reads DATABASE_URL.
Run: python scripts/build_pg_schema.py --output postgres_staging_schema.sql
"""
import argparse
from collections import defaultdict
from pathlib import Path
import re
import sqlite3

ROOT = Path(__file__).resolve().parents[1]
SOURCES = (ROOT / "control_tower.py", ROOT / "security_admin.py")
IDENTIFIER = re.compile(r"^[a-z][a-z0-9_]*$")


def quote(identifier):
    if not IDENTIFIER.fullmatch(identifier):
        raise ValueError("Unsafe SQL identifier: " + repr(identifier))
    return '"' + identifier + '"'


def sqlite_schema():
    """Load exactly the checked-in SQLite CREATE TABLE scripts in memory."""
    conn = sqlite3.connect(":memory:")
    for source in SOURCES:
        text = source.read_text(encoding="utf-8")
        match = re.search(r"conn\.executescript\(\s*\"\"\"(.*?)\"\"\"", text, re.S)
        if not match:
            raise ValueError("Could not find initial schema in " + source.name)
        conn.executescript(match.group(1))
    # SQLite ALTER TABLE additions from control_tower.init_db().
    text = SOURCES[0].read_text(encoding="utf-8")
    additions = re.findall(
        r'ensure_column\(conn,\s*"([a-z_]+)",\s*"([a-z_]+)",\s*"([^"]+)"\)',
        text,
    )
    for table, column, definition in additions:
        conn.execute(
            "ALTER TABLE " + quote(table) + " ADD COLUMN " + quote(column) + " " + definition
        )
    return conn


def column_type(sqlite_type):
    kind = sqlite_type.upper()
    if kind == "INTEGER":
        return "BIGINT"
    if kind == "REAL":
        return "DOUBLE PRECISION"
    if kind == "TEXT":
        return "TEXT"
    raise ValueError("Unrecognized SQLite type: " + sqlite_type)


def default_sql(value, target_type):
    if value is None:
        return ""
    if value.upper() == "CURRENT_TIMESTAMP":
        # Existing application stores timestamps as strings.
        return " DEFAULT CURRENT_TIMESTAMP::text"
    return " DEFAULT " + value


def create_table_sql(conn, table):
    info = conn.execute("PRAGMA table_info(" + quote(table) + ")").fetchall()
    pk_cols = [row for row in info if row[5]]
    identity = len(pk_cols) == 1 and pk_cols[0][2].upper() == "INTEGER"
    lines = []
    for _, name, dtype, notnull, default, pk in info:
        if identity and pk:
            col = quote(name) + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        else:
            col = quote(name) + " " + column_type(dtype)
            if notnull or pk:
                col += " NOT NULL"
            col += default_sql(default, dtype)
        lines.append(col)
    if not identity and pk_cols:
        lines.append("PRIMARY KEY (" + ", ".join(quote(r[1]) for r in sorted(pk_cols, key=lambda r: r[5])) + ")")
    for index in conn.execute("PRAGMA index_list(" + quote(table) + ")"):
        # origin 'u' = explicit UNIQUE constraint, 'pk' already handled.
        if index[3] != "u":
            continue
        cols = [r[2] for r in conn.execute("PRAGMA index_info(" + quote(index[1]) + ")")]
        lines.append("UNIQUE (" + ", ".join(quote(c) for c in cols) + ")")
    return "CREATE TABLE " + quote(table) + " (\n    " + ",\n    ".join(lines) + "\n);"


def foreign_key_sql(conn, table):
    """Create foreign keys after every table exists, avoiding forward-reference errors."""
    groups = defaultdict(list)
    for key in conn.execute("PRAGMA foreign_key_list(" + quote(table) + ")"):
        groups[key[0]].append(key)
    statements = []
    for fk_id, group in sorted(groups.items()):
        ordered = sorted(group, key=lambda r: r[1])
        name = quote("fk_" + table + "_" + str(fk_id))
        statements.append(
            "ALTER TABLE " + quote(table) + " ADD CONSTRAINT " + name +
            " FOREIGN KEY (" + ", ".join(quote(r[3]) for r in ordered) + ") " +
            "REFERENCES " + quote(ordered[0][2]) + " (" +
            ", ".join(quote(r[4]) for r in ordered) + ");"
        )
    return statements


def generate(schema="ct_staging"):
    quote(schema)
    with sqlite_schema() as conn:
        tables = [
            r[0] for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY rowid"
            )
        ]
        result = [
            "-- GENERATED staging DDL. REVIEW BEFORE APPLYING. Never execute against production.",
            "-- Does not copy data, change the Streamlit backend, or access any credentials.",
            "BEGIN;",
            "CREATE SCHEMA IF NOT EXISTS " + quote(schema) + ";",
            "SET LOCAL search_path TO " + quote(schema) + ";",
        ]
        result.extend(create_table_sql(conn, table) for table in tables)
        # PostgreSQL rejects inline foreign keys pointing to not-yet-created tables.
        for table in tables:
            result.extend(foreign_key_sql(conn, table))
        result.append("COMMIT;")
        return "\n\n".join(result) + "\n", tables


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", default="ct_staging")
    parser.add_argument("--output", type=Path, default=ROOT / "postgres_staging_schema.sql")
    args = parser.parse_args()
    sql, tables = generate(args.schema)
    args.output.write_text(sql, encoding="utf-8")
    print("Generated " + str(len(tables)) + " tables in " + str(args.output))


if __name__ == "__main__":
    main()
